apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.9.0/deploy/prerequisite/longhorn-nfs-installation.yaml
  - longhorn.namespace.yaml
  - longhorn.helm-release.yaml
  - longhorn.rwx.storage-class.yaml
