{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAvcRvZ/y9kqoOhkLHCNu6F9xwThFoCm1K5g5OcgYPaEFaeI8lGGAXrdyNOWFaW4Bs+eJ+4WbkEIEb2Ku8NRlNBhqaW7gtaYdTs6a+FlGASUngsjjVpH3NreB1CtG9cgCSqiLsrN8cPffiMiP/uesTyxcyhcBGrIf06sR8NjiY7p800i28BJluKJLMuwuxeQUD8a9zNphXQ3ka4YsEwbyxZLv7hFfRqgd4EmyeOFeUHY0fxQXHatjdL/KlD7rqjQMcNOb1b3h5ifoqQa0jfEkwY0bOSz3hHS+Bu4StG69UzXLt8ZYQ9LWVoYb5A7cSdp3cMPjo3tbbp0u0YHIaA9ExHC505YULr9aIa2oliij8ZmwZDE3XM3ER4dhqILDRP9Gjw6ko/ciyiE74Z9qyMM4HOO0cZ7+v8GyBNzlScFPDxeYrz0sRgRIQlKmJtPZ2k2tpR/iMGKNmt9b+PoW5gFwGaZ4ekz0xynvYh0vls+ILzDcDiTsRSqfa0zUxTn9X0aL31yVkb2EKUk7jA4sv0NAQxHeRJt6qW51QfGESPdkboxNd5Gg/nh2ogDBcK4kVqbYesiX4wmGxBD6kvXB/6EMqrJvC3Z9+AzEESFKa7YvBq2Qr6i/C5VcNVuwh6pmPOkS1zDex+zDtWX9ME4TtQ992aGNZS+ghe2/OLK42E7C43DXxerszanROQ2/hCzsuPAGgyCO/NAsJjg9CthpXQpm0k1bS1ew==",
      "AWS_ENDPOINTS": "AgAoyzo++gBOFQz5ANmdF+4xHA/c1BES3erm6cwp7N/gIgZ6P7W0+JP8NhPkBbHpSaJlV3l3AkPBrQBKy0u9Le8mtOTzu+/LuPwqIjm2u3MqiiTxPRe4Q2kiYBhCgQbEErmFCCGRvAlL+oBwH0HDQtz7eCdw5EG+ZmUB5HDzq4f+nDh42A24u7PawCucD/6+nHyF0+r2fFyKS/BVNrJnuXalugnG7Sk7pfFOd5wVf5cJwJ3wIcEspd9S9EeWAbFqXPEvHMdyDXiMD03jwH3GsVRIw38H/lXxE1ap51wnMQfqJlqemU3IcIce2epEw23kESWh2SgFqBdV2ALruioALersg5oVfLUCb6QoPIHGbAKgMovw+/5NVacGTi+1KQThzZmOls1uAojmnbcTchA+ESASxF+wgpoYw5b8LJgKiYRAOcWaawnsWsBDVTZI09leruBJM2MZskS83AeNUwcPQNmTChTb3I0Tvys3G4kFGKvO7YMBB5lvN/koVBGlIz1P0Ibz/j1uiOydddI63Nex9WIQp3TTPJHP3QIaEv//PjuFeS9BPf+OamVOQDGo4Kmrl1Ufr8sHU6vo4AfRhTAu8dysXbMHLleQnXcj4YfknUrm5kf6D4BIJgbD1y0vdOYLG+2eLoff3CklMnNlQc83gSxr5aOISzpR5HDXnw0rXm14NRJaUK6ZYqWRVjNeWJhY2i4oXXzzkbumRX+jnQFGcqb0KQk2X5wlvVw=",
      "AWS_SECRET_ACCESS_KEY": "AgCJU+oYtU25V4OadLCLSwUvgoCT/I5jEP/ERQZltabXSobyup1C2lacf8SpEPZ2++Fv+3tjwgiNqF39zJ8NgiNGaYOUfES0Lq43YvrruJWB6DwCO4cHhBjE0+BSLkIYicAg0qMpJKaZ2+a+o5cITez0fkU8KKHOSN8Xjfx5Juov8VIsg6g+qeoyLIZwAiyyQxNC4Z+1TJNcqldB4cTbU9F7++/fxdl8HG84Vhvt/jXwbCzMlVZjPeaBNUaEAEjQIJGemG8AR9huPNWP6OOIwzohjtGTNPWIZVOIKHBPrzcPdPHB4IOjTtI7y9EWENarBHR+Iu7tp43HlhE3WqQVW82BcJ5y6rB3vEwUxyFq+3L5FItCdDd0mhD8GrvRC0DLjZUM+l3NUE3foZopYvY8Zeuy1Y2yMnA3evPnx0UjT54QrC6BFWI3fyDPH6CxRiWp2lX7ZqkSAsBnVqHJ8bklFJyWcmwzxVv0Q7ByW04e50WYRh/kZamMioWidymUhOCf1S2FddPRcfrdY0wtgugA+T+SW3vLQpUjuKysmNZjNMGyeUEAKMFKdUDWlzRdt/x4j2QgWyY2rP3WosX4NzsZ8WdthadZnePlTfmU6Vhk0EpkFHFsRsRn/35Uem0WtggvM3jmR/ZmzKd4Y7zt8q35Eh/CkbB/zFEodLd+3XlJ3Vo8pJw1FnfcnD2JXm6aHjbM7x6s+sqwiPPFtVXmAqdhZo/EVpP7XtAGSFAJgxG4ASHca2M0tRmItC2g"
    }
  }
}
