apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: '9.1.11'
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: reflector
