apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/cloudnative-pg
  prune: true
  wait: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-repositories
    - name: longhorn-custom-resource-definitions
