apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: etcd-configs
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/overlays/production/etcd/configs
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sealed-secrets-production