apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  timeout: 5m
  releaseName: longhorn
  values:
    persistence:
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
    defaultBackupStore:
      backupTarget: s3://tinyrack@ap-northeast-2/longhorn
      backupTargetCredentialSecret: tinyrack-s3-secret