apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-release
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "*"
  values:
    apiServerProxyConfig:
      mode: "noauth"
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth-secret
      valuesKey: CLIENT_ID
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth-secret
      valuesKey: CLIENT_SECRET
      targetPath: oauth.clientSecret