apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-release
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: '2.17.3'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: sealed-secrets
  values:
    secretName: tinyrack-production-key
